PhluffyShuffy/PhluffyShuffyWeb/Models/ImageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhluffyShuffyWeb.Models
{
    public class ImageModel
    {
        public string Id { get; set; }

        public bool IsReadonly { get; set; }

        public IEnumerable<Uri> ImageParts { get; set; }
    }
}

PhluffyShuffy/PhluffyShuffyWeb/Controllers/ShuffleController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web;
using System.Web.Mvc;
using PhluffyShuffyWeb.Models;
using PhluffyShuffyWebData;

namespace PhluffyShuffyWeb.Controllers
{
    public class ShuffleController : Controller
    {
        private readonly IImageStorage storage;

        public ShuffleController()
            : this(new AzureImageStorage(ConfigurationManager.ConnectionStrings["AzureWebJobsStorage"].ConnectionString))
        {
        }

        public ShuffleController(IImageStorage imageStorage)
        {
            if (imageStorage == null)
            {
                throw new ArgumentNullException("imageStorage");
            }

            this.storage = imageStorage;
        }

        public ViewResult Index(string id = null)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                // Create a string that is valid for azure container naming
                id = Guid.NewGuid().ToString("N").ToLower();
            }

            ImageModel model = new ImageModel()
            {
                Id = id,
                ImageParts = this.storage.GetAllShuffleParts(id),
                IsReadonly = this.storage.IsReadonly(id)
            };

            return View(model);
        }

        [HttpGet]
        public JsonResult ShufflePath(string shuffleId)
        {
            Uri shuffleLink = this.storage.GetImageLink(shuffleId);

            JsonResult result;
            if (shuffleLink == null)
            {
                this.Response.StatusCode = 404;
                result = Json(null, JsonRequestBehavior.AllowGet);
            }
            else
            {
                result = Json(shuffleLink.ToString(), JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpPost]
        public ActionResult Upload(string shuffleId, IEnumerable<HttpPostedFileBase> files)
        {
            foreach(HttpPostedFileBase file in files)
            { 
                this.storage.AddNewPart(shuffleId, file.FileName, file.InputStream);
            }

            return RedirectToAction("Index", new { id = shuffleId });
        }

        [HttpPost]
        public ActionResult Create(string shuffleId)
        {
            this.storage.RequestShuffle(shuffleId);

            return RedirectToAction("Index", new { id = shuffleId });
        }
    }
}

PhluffyShuffy/PhluffyShuffyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PhluffyShuffy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("PhluffyShuffy", "Index", "Shuffle", new { id = (int?)null }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PhluffyShuffy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PhluffyShuffy/PhluffyShuffyWeb/Views/Shuffle/Index.cshtml
@model PhluffyShuffyWeb.Models.ImageModel

@{
    ViewBag.Title = "Index";
}

@if (!Model.IsReadonly)
{ 
    <h1>Add images</h1>
    <br />
        
    using (Html.BeginForm("Upload", "Shuffle", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    <input type="hidden" name="shuffleId" value="@Model.Id">
    <input type="file" name="files" multiple />
    
    <br />
    <input type="submit" name="Upload" value="Upload" />
    }
}

@if (Model.ImageParts.Any())
{ 
    <h1>Images</h1>

    if(!Model.ImageParts.Any())
    {
        <p>No image uploaded yet</p>
    }
    else
    {
        foreach(Uri imageUri in Model.ImageParts)
        {
            <img src="@imageUri.ToString()" alt="imagePart" width="150" />
        }
    }
}

@if(Model.ImageParts.Count() > 1)
{ 
    if (!Model.IsReadonly)
    { 
        <h1>Ready?</h1>
        using (Html.BeginForm("Create", "Shuffle", FormMethod.Post))
        {
            <input type="hidden" name="shuffleId" value="@Model.Id">
            <input type="submit" name="Create" value="Shuffle" />
        }
    }
    else
    {
        <h1>Result</h1>
        <div id="imageResult">
            <p>
                Your image is being created and will show up here once it is done.<br />
                If you do not want to wait, use @Html.ActionLink("this link", "Index", new { id = Model.Id }) to come back later.
            </p>
        </div>
    }
}
else
{
    <p>Upload at least 2 images to continue.</p>
}

@if (Model.IsReadonly)
{ 
    <script type="text/javascript">
        function GetResultImage() {
            var options = {};
            options.url = "/Shuffle/ShufflePath?shuffleId=@Model.Id";
            options.type = "GET";
            options.dataType = "json";
            options.contentType = "application/json";
            options.timeout = 10000;
            options.success = function (data) {
                $(imageResult).html('<a href=' + data + '><img width="250" src=' + data + ' /></a>')
            };
            options.error = function () {
                setTimeout(function () {
                    $.ajax(options)
                }, 10000);
            }

            $.ajax(options);
        }

        GetResultImage();
    </script>
}